### ISSUE TITLE
insert tasks in meilisearch

### ISSUE THREAD

**Issue by irevoire** [db-benchmarks/db-benchmarks#27]
Hey, I was wondering why it was taking so long to ingest a dataset we’ve successfully inserted into meilisearch a few times in a few hours, so I skimmed at your script quickly, and I’m wondering, why do you stop meilisearch from autobatching your tasks?
This looks super inefficient.
https://github.com/db-benchmarks/db-benchmarks/blob/92e1dd6ac5fad14f8ce5d9b83776de080f792fb5/misc/func.sh#L49-L56

Another thing, if you’re using the hacker news dataset I think you’re using, then it would probably be better to set some `searchableAttributes`. From what I see in the one we used, it looks like that;
```json
{
  "by" : "dhouston",
  "descendants" : 71,
  "id" : 8863,
  "kids" : [ 8952, 9224, 8917, 8884, 8887, 8943, 8869, 8958, 9005, 9671, 8940, 9067, 8908, 9055, 8865, 8881, 8872, 8873, 8955, 10403, 8903, 8928, 9125, 8998, 8901, 8902, 8907, 8894, 8878, 8870, 8980, 8934, 8876 ],
  "score" : 111,
  "time" : 1175714200,
  "title" : "My YC app: Dropbox - Throw away your USB drive",
  "type" : "story",
  "url" : "http://www.getdropbox.com/u/2/screencast.html"
}
```

It’s pretty obvious that no one wants to search in the `id`, `kids`, `score`, `time`, `type`, or `url`. The only thing that’s really useful seems to be the `title` actually 😬 
This is the settings we used in our tests if you’re interested;
```json
{
	"displayedAttributes": [
	  "title",
	  "by",
	  "score",
	  "time"
	],
	"searchableAttributes": [
	  "title"
	],
	"filterableAttributes": [
	  "by"
	],
	"sortableAttributes": [
	  "score",
	  "time"
	]
}
```

On our side we were able to ingest the 33M hacker news documents in less than 2h on a random macbook pro M1 iirc (it was a long time ago, probably in v0.30)

**Comment by sanikolaev** [comment]
Thank you for your comment @irevoire 

>  I’m wondering, why do you stop meilisearch from autobatching your tasks? This looks super inefficient.

The script makes sure there's exactly 8 running loading tasks at the same time. As soon as it becomes 7, another task is added to the queue. What's wrong with it? What would be a better solution?

> then it would probably be better to set some searchableAttributes.

We didn't set `searchableAttributes` since as said in the docs https://www.meilisearch.com/docs/reference/api/settings#searchable-attributes 

> By default, the searchableAttributes array is equal to all fields in your dataset.

We set `filterableAttributes` and `sortableAttributes` though here https://github.com/db-benchmarks/db-benchmarks/blob/92e1dd6ac5fad14f8ce5d9b83776de080f792fb5/tests/hn/meilisearch/init#L21-L32

Did we do anything wrong?

> On our side we were able to ingest the 33M hacker news documents in less than 2h

I would appreciate it if you could share the script, so we can learn from it. Ours are entirely open-source, from preparing the dataset to making search queries. If you follow the instructions in the [readme](https://github.com/db-benchmarks/db-benchmarks/blob/main/README.md) you can reproduce it too. I'll be happy to help you in case something is not clear.

It will be even better if you fix the meilisearch data ingestion script we used, so it loads data into Meilisearch faster. I'll be happy to accept your PR.

**Comment by irevoire** [comment]
> The script makes sure there's exactly 8 running loading tasks at the same time. As soon as it becomes 7, another task is added to the queue. What's wrong with it? What would be a better solution?

You should let meilisearch process as many tasks as it wants, the « normal way » is to just send everything in the largest batch possible and then let meilisearch handle the rest.

> We didn't set searchableAttributes since as said in the docs https://www.meilisearch.com/docs/reference/api/settings#searchable-attributes
>
>>    By default, the searchableAttributes array is equal to all fields in your dataset.

Yeah it works; you're just indexing a lot of fields you don't need. I don't have your dataset (and it seems like we didn't use the same in our tests), so I don't really know how many fields are useful in it, but in general, for better relevancy and performance, you should try to only index the « text fields ». Making fields.

> I would appreciate it if you could share the script, so we can learn from it.

We didn't keep it, sorry :pensive:
That wasn't a benchmark; we were just checking if meilisearch could handle this dataset and in how much time.

> It will be even better if you fix the meilisearch data ingestion script we used so it loads data into Meilisearch faster. I'll be happy to accept your PR.

I'll be honest, I don't really have the time to dive into your scripts, I'll submit a PR for the bash script, which seems easy, but I can't find the documents of your datasets in the repo, and I don't plan to install docker just to download a text file. If you can give me one document of the dataset, I could probably give you some settings to go with it though.

**Comment by sanikolaev** [comment]
> You should let meilisearch process as many tasks as it wants

OK, no problem. I'll make the change tomorrow, so it creates 1169 loading tasks right away. I'll keep you informed.

> the « normal way » is to just send everything in the largest batch possible and then let meilisearch handle the rest.

Can you please confirm it really makes sense and is supposed to be beneficial to upload a 69GB csv into Meilisearch with a single curl call?

```
root@perf3 /perf/test_engines/tests/hn/data # ls -lah data.csv
-rwxrwxrwx 1 systemd-coredump root 69G Mar  2 16:06 data.csv
```

> Yeah it works; you're just indexing a lot of fields you don't need

Please confirm we should override `searchableAttributes` and leave in the array only those fields that are applicable for full-text search despite the fact that the other fields are numeric. You can see what the schema looks like here https://github.com/db-benchmarks/db-benchmarks/blob/main/tests/hn/es/logstash_tuned/template.json#L8-L19 .

> If you can give me one document of the dataset, I could probably give you some settings to go with it though.

Here you go:
```
root@perf3 /perf/test_engines/tests/hn/data # head data.csv.fix
id:number,story_id:number,story_text,story_author,comment_id:number,comment_text,comment_author,comment_ranking:number,author_comment_count:number,story_comment_count:number
"1","3985069","","joedev","3985756","Makes sense for Verizon, and if they are being greedy, others will step in to fill the void.","Quizzy","10","11","13"
"2","2481190","","soitgoes","2481521","""Made to play"" is a contradiction.","petervandijck","9","1125","16"
"3","6302825","","adriano_f","6303075","I like this a lot!<p>The research manuscript example is exciting. It would be great if authors could link directly to the part of a paper that they are citing and be able to open that up if you want to dive deeper. Linking methods to results to discussion for specific experiments would make reading through dense papers a lot easier, and maybe have a notation&#x2F;jargon definition section open at the same time. It&#x27;s almost like a tiling window manager for reading.<p>I&#x27;m a little bit concerned about how it looks on smaller screens. It looks fine on my work monitor but I only have a netbook at home right now and a lot of websites have overlapping elements that keep me from reading articles. I haven&#x27;t looked at this from that computer yet though. Maybe it would help to have collapsible columns if there are issues.<p>Good luck, I&#x27;m looking forward to seeing where this goes!","heurist","5","31","42"
"4","6268480","","bpierre","6270567","Fetching stuff over HTTP can be incredibly stupid. I there is a security list out there that some little firewall company decided to have their devices automatically download. The list doesn&#x27;t change that often, but every single device that company made likes to check every 10 minutes or so. Nothing can stop them, they follow Wilya&#x27;s algorithm [1].<p>[1] <a href=""https://news.ycombinator.com/item?id=6268919"" rel=""nofollow"">https:&#x2F;&#x2F;news.ycombinator.com&#x2F;item?id=6268919</a><p>Side note: it&#x27;s sad to see that Apple is a huge perpetrator in this one. I hope they fix that bug.","MBCook","5","84","11"
"5","5487883","","jpadilla_","5487972","Conversely, start working( harder ).","TheSOB88","43","171","44"
"6","4489556","","denzil_correa","4489696","I wonder if Facebook gets subsidies... It's an Orwellian paradise.<p>And let's not forget Google too - they have Picasa, Google+, Android face unlocking...","qwertzlcoatl","6","61","24"
"7","2151674","","jaltucher","2152347","I go to a university (BYU) with annual tuition of 5k.  My wife also attends and is on full-tuition scholarship.  I work part time, get Pell Grants, and will graduate in 4 years with zero debt.<-nl->otal monthly cost of living (for both of us) is $1200-$1500.<p>It's not MIT or Stanford, but it's a good school with plenty of opportunities.","phamilton","9","317","11"
"8","6302825","","adriano_f","6303520","Hopefully this criticism is helpful.<p>I find this really hard to read, sorry.<p>I can&#x27;t just scroll through or scan read, and I&#x27;m met with a variety of different things all at once. Everything&#x27;s always visible, so I don&#x27;t know what I&#x27;m looking at. I&#x27;ve scrolled down on the lowest level, and read a bit but have no understanding of the context. Clicking on it makes me realise where I am but I&#x27;ve skipped over a load of stuff in the middle so I&#x27;m scrolling back up that to find where I left off... I think this is a visual thing though rather than a major issue with the <i>idea</i>. Fiddling a bit I&#x27;ve only just found that not every node has children, but this this is only indicated by nothing happening (which is identical to something that should happen but doesn&#x27;t)<p>This is really a different formatter for the same structure of text we&#x27;ve already been using, so the hyperbole is a bit of a turnoff for me.<p><pre><code>    \section{some title}<-nl->   <-nl->   Explanatory text<-nl->   <-nl->   \subsection{subsection title}<-nl-><-nl->   Sub text<-nl->/code></pre><-nl->tc.<p>Or<p><pre><code>    &lt;section&gt;<-nl->       &lt;h1&gt;heading&lt;&#x2F;h1&gt;<-nl->       &lt;p&gt;Text&lt;&#x2F;p&gt;<-nl->       &lt;section&gt;<-nl->           &lt;h2&gt;heading 2<-nl-><-nl->/code></pre><-nl->hy do we need something new? What&#x27;s being added? What couldn&#x27;t I do before that&#x27;s now possible? These are the things I want to know when you tell me you&#x27;ve got a new hierarchical document. Can I already read these well with a screen-reader? The ordering in the source would (I think) read each column individually, which wouldn&#x27;t make sense. Try loading your viewer without CSS. Imagine a screenreader hitting the massive block of JSON at the bottom of the page. Why is that in the body?","IanCal","2","82","42"
"9","295847","","nreece","296586","When life gives you rotten apples, made cider.<p>(a problem is an opportunity).","13ren","8","169","12"
```

**Comment by irevoire** [comment]
> OK, no problem. I'll make the change tomorrow, so it creates 1169 loading tasks right away. I'll keep you informed.

I made a PR for you here; https://github.com/db-benchmarks/db-benchmarks/pull/28

> Can you please confirm it really makes sense and is supposed to be beneficial to upload a 69GB csv into Meilisearch with a single curl call?

Soooo, that would be nice, but by default, meilisearch limits the maximum payload size to 100MiB (it makes sense since meilisearch is often used behind a reverse proxy with the same limitation or even less).
Tbh, to keep the benchmarks fair & honest, I think we should keep the way you create your batch as-is.
We could probably improve it a little bit, but I feel like you did the kind of thing a « normal » user would do.

> Please confirm we should override searchableAttributes and leave in the array only those fields that are applicable for full-text search despite the fact that the other fields are numeric.

Yes exactly! I'll submit another PR, but basically, from what I see, only the `story_text` and `comment_text` should be set as searchable what do you think?
For the numeric fields, they should be either ignored, filterable/sortable/both  as you did :ok_hand: 
https://github.com/db-benchmarks/db-benchmarks/pull/29

**Comment by sanikolaev** [comment]
> Tbh, to keep the benchmarks fair & honest, I think we should keep the way you create your batch as-is.

OK. Thanks for checking.

Thank you for the PRs. I'll review/accept them tomorrow and will rerun the tests.

**Comment by irevoire** [comment]
Also, I was looking for the code running the search requests (I didn't find it, so if you know where it is, I would love to take a look), and I found this comment;
https://github.com/db-benchmarks/db-benchmarks/blob/92e1dd6ac5fad14f8ce5d9b83776de080f792fb5/plugins/meilisearch.php#L127-L130

Just FYI, meilisearch never caches anything, so there is nothing to clear.
Your kernel may cache some of the memory-mapped files we use, though, and I don't see any other way than rebooting to clear this.

**Comment by sanikolaev** [comment]
> Just FYI, meilisearch never caches anything, so there is nothing to drop.

Good to know. 

> I don't see any other way than rebooting to clear this.

FYI, there is a way - https://github.com/db-benchmarks/db-benchmarks/blob/92e1dd6ac5fad14f8ce5d9b83776de080f792fb5/test#L520-L523 . It requires restarting the engine though which the framework does.

**Comment by sanikolaev** [comment]
Now it's crashed another way. Here's what I see in the meilisearch docker output:

```
root@perf3 /perf/test_engines # docker-compose logs meilisearch
...
meilisearch_engine | thread 'indexing-thread:15' panicked at 'the allocator is unable to allocate that much memory (41666672 bytes requested)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs:350:9
meilisearch_engine | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
meilisearch_engine | thread 'indexing-thread:17' panicked at 'the allocator is unable to allocate that much memory (41666672 bytes requested)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs:350:9
meilisearch_engine | thread 'indexing-thread:7' panicked at 'the allocator is unable to allocate that much memory (41666672 bytes requested)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs:350:9
meilisearch_engine | thread 'indexing-thread:12' panicked at 'the allocator is unable to allocate that much memory (41666672 bytes requested)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs:350:9
meilisearch_engine | thread 'indexing-thread:17' panicked at 'the allocator is unable to allocate that much memory (41666672 bytes requested)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rsthread ':350indexing-thread:15:' panicked at '9the allocator is unable to allocate that much memory (41666672 bytes requested)
meilisearch_engine | ', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs:350:9
meilisearch_engine | memory allocation of 24 bytes failed
```

The server has 128GB of RAM.

@irevoire would it make sense to get back to the initial idea of letting Meilisearch process exactly 8 loading tasks at once? Maybe a higher number makes sense, but lower than 1167?

**Comment by sanikolaev** [comment]
When it doesn't crash entirely, so I can send a query to the tasks API, it's full of:

```
    {
      "uid": 1151,
      "indexUid": "hn",
      "status": "failed",
      "type": "documentAdditionOrUpdate",
      "canceledBy": null,
      "details": {
        "receivedDocuments": 100000,
        "indexedDocuments": 0
      },
      "error": {
        "message": "An unexpected crash occurred when processing the task.",
        "code": "internal",
        "type": "internal",
        "link": "https://docs.meilisearch.com/errors#internal"
      },
      "duration": "PT3262.972129499S",
      "enqueuedAt": "2023-05-05T12:34:01.816653465Z",
      "startedAt": "2023-05-05T13:32:51.058971901Z",
      "finishedAt": "2023-05-05T14:27:14.0311014Z"
    },
```

and the meilisearch docker says:
```
meilisearch_engine | thread 'thread 'indexing-thread:8indexing-thread:16' panicked at '' panicked at 'the allocator is unable to allocate that much memory (41666672 bytes requested)the allocator is unable to allocate that much memory (41666672 bytes requested)', ', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs::350350:9:
meilisearch_engine | 9note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
meilisearch_engine |
meilisearch_engine | thread 'indexing-thread:17' panicked at 'the allocator is unable to allocate that much memory (41666672 bytes requested)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs:350:9
meilisearch_engine | thread 'indexing-thread:8' panicked at 'the allocator is unable to allocate that much memory (41666672 bytes requested)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs:350:9
meilisearch_engine | thread 'indexing-thread:8' panicked at 'the allocator is unable to allocate that much memory (41666672 bytes requested)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs:350:9
meilisearch_engine | thread 'indexing-thread:8' panicked at 'the allocator is unable to allocate that much memory (41666672 bytes requested)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs:350:9
meilisearch_engine | thread 'indexing-thread:8' panicked at 'the allocator is unable to allocate that much memory (41666672 bytes requested)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs:350:9
meilisearch_engine | thread 'indexing-thread:8' panicked at 'the allocator is unable to allocate that much memory (41666672 bytes requested)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs:350:9
meilisearch_engine | thread 'indexing-thread:16' panicked at 'the allocator is unable to allocate that much memory (41666672 bytes requested)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs:350:9
meilisearch_engine | thread 'indexing-thread:16' panicked at 'the allocator is unable to allocate that much memory (41666672 bytes requested)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs:350:9
meilisearch_engine | thread 'indexing-thread:8' panicked at 'the allocator is unable to allocate that much memory (41666672 bytes requested)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/grenad-0.4.4/src/sorter.rs:350:9
```

**Comment by sanikolaev** [comment]
https://github.com/meilisearch/meilisearch/issues/4127 may be somehow related.

**Comment by irevoire** [comment]
Hey, sorry I never went back to you and I just found this issue again.
So, as you can see right above, we fixed the issue you were encountering a looong time ago.
We also rewrote the whole indexing pipeline of Meilisearch in the past 4 months, it should be released next Monday.

In case that helps, we also made a tool that splits your dataset into smaller chunks that Meilisearch can ingest [here](https://github.com/meilisearch/meilisearch-importer).

Let me know if you ever try the latest version of Meilisearch.

**Comment by sanikolaev** [comment]
Thanks for letting me know, @irevoire.

@djklim87, please take a look at the tool @irevoire mentioned.

We are currently [working](https://github.com/db-benchmarks/db-benchmarks/issues/37) on a global retest using the latest versions of all the engines and databases.

**Comment by djklim87** [comment]
I can’t upload the dataset using the provided importer. Maybe I am doing something wrong.

Related issue: https://github.com/meilisearch/meilisearch-importer/issues/24
